[tool.black]
skip-string-normalization = true

[tool.poetry]
name = "yearn-data-analytics"
version = "0.3.0"
description = ""
authors = [
    "borrito <yh01dlx@gmail.com>",
    "huggingbot <83656073+huggingbot@users.noreply.github.com>",
]
packages = [
    { include = "helpers" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
python-dotenv = "0.16.0"
requests = "2.27.1"
web3 = "5.27.0"
pandas = "1.4.2"
requests-toolbelt = "0.9.1"
joblib = "1.2.0"
altair = "4.2.0"
datapane = "0.15.3"
scipy = "1.9.2"
tqdm = "4.64.1"

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
mypy = "0.950"
black = "22.3.0"
isort = "5.10.1"
pre-commit = "2.19.0"
pre-commit-hooks = "4.2.0"
types-requests = "2.27.29"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
